export const hotelTypes = [
    "Barato",
    "Compartilhado",
    "Luxuoso",
    "Skiar",
    "Negocios",
    "Familia",
    "Romantico",
    "Livre",
    "Cabana",
    "Praia",
    "Campo",
    "Interior",
    "Tudo Incluso",
    "Com Pets",
    "Auto-Atendimento",
  ];
  
  export const hotelFacilities = [
    "Wi-fi",
    "Estacionamento",
    "Objetos de Cozinha",
    "Quartos pra Familia",
    "Quartos para não fumantes",
    "Piscina Exterior",
    "Spar",
    "Academia",
    "Area de Esportes",
    "Só para Casal",
  ];